services:
  postgres:
    image: postgres:latest
    container_name: ezpay-postgres
    environment:
      POSTGRES_DB: ezpaydb
      POSTGRES_USER: milagrossachetti
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"

